server:
  port: 8102
  servlet:
    context-path: /happy
spring:
  application:
    name: ms-product
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:product-db;MODE=PostgreSQL
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    fetch-registry: true